services:
  grab:
    build: .
    container_name: grab
    restart: unless-stopped
    ports:
      - "5008:5008"
    environment:
      YTDLP_PROXY: ${YTDLP_PROXY:-}
    networks:
      - web

networks:
  web:
    external: true
